apiVersion: apps/v1
kind: Deployment
metadata :
  name: nodeport
  labels:
    app: ngx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: ngx
  template: 
    metadata:
      labels:
        app: ngx
    spec:
      containers:
      - name: nodeport
        image: nginx
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: ngx
spec:
  selector:
    app: ngx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80